# -*- coding: utf-8 -*-
"""SQL Queries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h-0uTnrxsyfalfOtWplMz-g6rN7mcfkk
"""

# Reading CSV file
import pandas as pd
data = pd.read_csv("/content/adm_data.csv")
data.head()

data = data.drop('Serial No.', axis=1)

data.head()

"""### **Creating A Database and A Table**"""

import sqlite3

# Connecting to the SQLite database
conn = sqlite3.connect('University_database.db')

# Creating a cursor object
cursor = conn.cursor()

# Creating a new table named 'admissions'
cursor.execute('''
    CREATE TABLE admissions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        GRE_Score INTEGER,
        TOEFL_Score INTEGER,
        University_Rating INTEGER,
        SOP REAL,
        LOR REAL,
        CGPA REAL,
        Research INTEGER,
        Chance_of_Admit REAL
    )
''')

# Committing the transaction
conn.commit()

"""### **Inserting into the Table**"""

for _, row in data.iterrows():
    cursor.execute('''
        INSERT INTO admissions (GRE_Score, TOEFL_Score, University_Rating, SOP, LOR, CGPA, Research, Chance_of_Admit)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        row['GRE Score'], row['TOEFL Score'], row['University Rating'],
        row['SOP'], row['LOR '], row['CGPA'], row['Research'], row['Chance of Admit ']
    ))

# Committing the transaction
conn.commit()

"""### **Extracting all data**"""

conn = sqlite3.connect('University_database.db')

# Creating a cursor object
cursor = conn.cursor()
cursor.execute("SELECT * FROM admissions")
column_names = [description[0] for description in cursor.description]
# Fetching all the rows
rows = cursor.fetchall()

df = pd.DataFrame(rows, columns=column_names)

# Print the DataFrame
print(df.head())

conn.close()

"""### **Specific Queries**"""

# select id's of students with GRE_Score>320, TOEFL_Score<110 and still have Chance_of_Admit>75%
conn = sqlite3.connect('University_database.db')

# Creating a cursor object
cursor = conn.cursor()
cursor.execute("SELECT id FROM admissions WHERE GRE_Score>320 AND TOEFL_Score<110 AND Chance_of_Admit>0.75")
column_names = [description[0] for description in cursor.description]
# Fetching all the rows
rows = cursor.fetchall()

df = pd.DataFrame(rows, columns=column_names)

# Print the DataFrame
print(df.head())

conn.close()

"""### **Transforming Data**"""

# Update research value of student whose id=1
conn = sqlite3.connect('University_database.db')

# Creating a cursor object
cursor = conn.cursor()
cursor.execute("UPDATE admissions SET Research=0 WHERE id=1")
conn.commit()
cursor.execute("SELECT * FROM admissions LIMIT 5")
column_names = [description[0] for description in cursor.description]
# Fetching all the rows
rows = cursor.fetchall()

df = pd.DataFrame(rows, columns=column_names)

# Print the DataFrame
print(df.head())
conn.close()

